source_entity: DCRA
base_url: https://maps.commerce.alaska.gov/server/rest/services/Demographics/Alaska_American_Community_Survey/MapServer/3/query?outFields=*&where=End_Year%3D2023&f=geojson
format: geojson
